/**
 * @file get_info.cpp
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
// #define OUTPUT_DEBUG
#include "v1_3.hpp"

#include <string>

#include "mediafire_sdk/api/error.hpp"
#include "mediafire_sdk/api/ptree_helpers.hpp"
#include "mediafire_sdk/utils/string.hpp"
#include "mediafire_sdk/api/session_token_api_base.hpp"

#include "boost/property_tree/json_parser.hpp"

namespace v1_3 = mf::api::user::get_info::v1_3;


#include "mediafire_sdk/api/type_helpers.hpp"

namespace {
// get_data_type_struct_extractor begin
using namespace v1_3;  // NOLINT
bool FacebookFromPropertyBranch(
        Response * response,
        ResponseData::Facebook * value,
        const boost::property_tree::wptree & pt
    )
{
#   define return_error(error_type, error_message)                             \
    {                                                                          \
        response->error_code = make_error_code( error_type );                  \
        response->error_string = error_message;                                \
        return false;                                                          \
    }
    using mf::api::GetIfExists;
    using mf::api::GetValueIfExists;
    if (pt.size() == 0)  // Stop if branch is empty
        return false;

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "facebook_id",
                &optarg) )
        {
            value->id = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "date_created",
                &optarg) )
        {
            value->date_created = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "facebook_url",
                &optarg) )
        {
            value->url = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "name",
                &optarg) )
        {
            value->name = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "firstname",
                &optarg) )
        {
            value->firstname = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "lastname",
                &optarg) )
        {
            value->lastname = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "hometown",
                &optarg) )
        {
            value->hometown = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "location",
                &optarg) )
        {
            value->location = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "i18n",
                &optarg) )
        {
            value->i18n = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        int32_t optarg;
        if ( GetIfExists(
                pt,
                "timezone",
                &optarg) )
        {
            value->timezone = optarg;
        }
    }

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                pt,
                "linked",
                &optval) )
        {
            if ( optval == "no" )
                value->linked = Linked::No;
            else if ( optval == "yes" )
                value->linked = Linked::Yes;
        }
    }

    // get_data_type_struct_extractor conclusion
    return true;
#   undef return_error
}
// get_data_type_struct_extractor begin
using namespace v1_3;  // NOLINT
bool TwitterFromPropertyBranch(
        Response * response,
        ResponseData::Twitter * value,
        const boost::property_tree::wptree & pt
    )
{
#   define return_error(error_type, error_message)                             \
    {                                                                          \
        response->error_code = make_error_code( error_type );                  \
        response->error_string = error_message;                                \
        return false;                                                          \
    }
    using mf::api::GetIfExists;
    using mf::api::GetValueIfExists;
    if (pt.size() == 0)  // Stop if branch is empty
        return false;

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "twitter_id",
                &optarg) )
        {
            value->id = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "date_created",
                &optarg) )
        {
            value->date_created = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "screen_name",
                &optarg) )
        {
            value->screen_name = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "name",
                &optarg) )
        {
            value->name = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "i18n",
                &optarg) )
        {
            value->i18n = optarg;
        }
    }

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                pt,
                "linked",
                &optval) )
        {
            if ( optval == "no" )
                value->linked = Linked::No;
            else if ( optval == "yes" )
                value->linked = Linked::Yes;
        }
    }

    // get_data_type_struct_extractor conclusion
    return true;
#   undef return_error
}
// get_data_type_struct_extractor begin
using namespace v1_3;  // NOLINT
bool GmailFromPropertyBranch(
        Response * response,
        ResponseData::Gmail * value,
        const boost::property_tree::wptree & pt
    )
{
#   define return_error(error_type, error_message)                             \
    {                                                                          \
        response->error_code = make_error_code( error_type );                  \
        response->error_string = error_message;                                \
        return false;                                                          \
    }
    using mf::api::GetIfExists;
    using mf::api::GetValueIfExists;
    if (pt.size() == 0)  // Stop if branch is empty
        return false;

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "gmail_id",
                &optarg) )
        {
            value->id = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        boost::posix_time::ptime optarg;
        if ( GetIfExists(
                pt,
                "created",
                &optarg) )
        {
            value->created = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "email",
                &optarg) )
        {
            value->email = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "gmail_url",
                &optarg) )
        {
            value->url = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "name",
                &optarg) )
        {
            value->name = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "firstname",
                &optarg) )
        {
            value->first_name = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "lastname",
                &optarg) )
        {
            value->last_name = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                pt,
                "i18n",
                &optarg) )
        {
            value->i18n = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        boost::posix_time::ptime optarg;
        if ( GetIfExists(
                pt,
                "synced",
                &optarg) )
        {
            value->synced = optarg;
        }
    }

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                pt,
                "linked",
                &optval) )
        {
            if ( optval == "no" )
                value->linked = Linked::No;
            else if ( optval == "yes" )
                value->linked = Linked::Yes;
        }
    }

    // get_data_type_struct_extractor conclusion
    return true;
#   undef return_error
}
}  // namespace

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
namespace get_info {
namespace v1_3 {

const std::string api_path("/api/1.3/user/get_info");

// Impl ------------------------------------------------------------------------

class Impl : public SessionTokenApiBase<Response>
{
public:
    Impl();

    virtual void BuildUrl(
        std::string * path,
        std::map<std::string, std::string> * query_parts
    ) const override;

    virtual void ParseResponse( Response * response ) override;

    mf::http::SharedBuffer::Pointer GetPostData();

    mf::api::RequestMethod GetRequestMethod() const override
    {
        return mf::api::RequestMethod::Post;
    }
};

Impl::Impl()
{
}

void Impl::BuildUrl(
            std::string * path,
            std::map<std::string, std::string> * /* query_parts */
    ) const
{
    *path = api_path + ".php";
}

void Impl::ParseResponse( Response * response )
{
    // This function uses return defines for readability and maintainability.
#   define return_error(error_type, error_message)                             \
    {                                                                          \
        SetError(response, error_type, error_message);                         \
        return;                                                                \
    }

    ResponseData response_data;

    // For uniformity for code generation with the other content parsers.
    ResponseData * response_data_ptr = &response_data;
    response_data_ptr->first_name = "";
    response_data_ptr->last_name = "";
    response_data_ptr->gender = Gender::Unknown;
    response_data_ptr->birth_date = boost::posix_time::not_a_date_time;
    response_data_ptr->created_datetime = boost::posix_time::not_a_date_time;

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.ekey",
            &response_data_ptr->ekey ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.ekey\"");

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.email",
            &response_data_ptr->email ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.email\"");

    // create_content_parse_single optional with default
    GetIfExists(
            response->pt,
            "response.user_info.first_name",
            &response_data_ptr->first_name);

    // create_content_parse_single optional with default
    GetIfExists(
            response->pt,
            "response.user_info.last_name",
            &response_data_ptr->last_name);

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.display_name",
            &response_data_ptr->display_name ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.display_name\"");

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                response->pt,
                "response.user_info.gender",
                &optval) )
        {
            if ( optval == "unknown" )
                response_data_ptr->gender = Gender::Unknown;
            else if ( optval == "male" )
                response_data_ptr->gender = Gender::Male;
            else if ( optval == "female" )
                response_data_ptr->gender = Gender::Female;
        }
    }

    // create_content_parse_single optional with default
    GetIfExists(
            response->pt,
            "response.user_info.birth_date",
            &response_data_ptr->birth_date);

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                response->pt,
                "response.user_info.location",
                &optarg) )
        {
            response_data_ptr->location = optarg;
        }
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                response->pt,
                "response.user_info.website",
                &optarg) )
        {
            response_data_ptr->website = optarg;
        }
    }

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                response->pt,
                "response.user_info.premium",
                &optval) )
        {
            if ( optval == "no" )
                response_data_ptr->account_type = AccountType::Basic;
            else if ( optval == "yes" )
                response_data_ptr->account_type = AccountType::Premium;
            else
                return_error(
                    mf::api::api_code::ContentInvalidData,
                    "invalid value in response.user_info.premium");
        }
        else
            return_error(
                mf::api::api_code::ContentInvalidData,
                "no value in response.user_info.premium");
    }

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.bandwidth",
            &response_data_ptr->bandwidth ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.bandwidth\"");

    // create_content_parse_single optional with default
    GetIfExists(
            response->pt,
            "response.user_info.created",
            &response_data_ptr->created_datetime);

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                response->pt,
                "response.user_info.validated",
                &optval) )
        {
            if ( optval == "no" )
                response_data_ptr->validated = Validated::NotValidated;
            else if ( optval == "yes" )
                response_data_ptr->validated = Validated::Validated;
            else
                return_error(
                    mf::api::api_code::ContentInvalidData,
                    "invalid value in response.user_info.validated");
        }
        else
            return_error(
                mf::api::api_code::ContentInvalidData,
                "no value in response.user_info.validated");
    }

    // create_content_parse_single optional no default
    {
        std::string optarg;
        if ( GetIfExists(
                response->pt,
                "response.user_info.tos_accepted",
                &optarg) )
        {
            response_data_ptr->tos_accepted = optarg;
        }
    }

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.used_storage_size",
            &response_data_ptr->used_storage_size ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.used_storage_size\"");

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.base_storage",
            &response_data_ptr->base_storage ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.base_storage\"");

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.bonus_storage",
            &response_data_ptr->bonus_storage ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.bonus_storage\"");

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.storage_limit",
            &response_data_ptr->storage_limit ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.storage_limit\"");

    {
        std::string optval;
        // create_content_enum_parse TSingle
        if ( GetIfExists(
                response->pt,
                "response.user_info.storage_limit_exceeded",
                &optval) )
        {
            if ( optval == "no" )
                response_data_ptr->storage_limit_exceeded = LimitExceeded::WithinBounds;
            else if ( optval == "yes" )
                response_data_ptr->storage_limit_exceeded = LimitExceeded::Exceeded;
            else
                return_error(
                    mf::api::api_code::ContentInvalidData,
                    "invalid value in response.user_info.storage_limit_exceeded");
        }
        else
            return_error(
                mf::api::api_code::ContentInvalidData,
                "no value in response.user_info.storage_limit_exceeded");
    }

    // create_content_parse_single required
    if ( ! GetIfExists(
            response->pt,
            "response.user_info.options",
            &response_data_ptr->options ) )
        return_error(
            mf::api::api_code::ContentInvalidData,
            "missing \"response.user_info.options\"");

    // create_content_struct_parse TSingle
    try {
        const boost::property_tree::wptree & branch =
            response->pt.get_child(L"response.user_info.facebook");

        ResponseData::Facebook optarg;
        if ( FacebookFromPropertyBranch(
                response, &optarg, branch) )
        {
            response_data_ptr->facebook = std::move(optarg);
        }
    }
    catch(boost::property_tree::ptree_bad_path & err)
    {
        // Is optional
    }

    // create_content_struct_parse TSingle
    try {
        const boost::property_tree::wptree & branch =
            response->pt.get_child(L"response.user_info.twitter");

        ResponseData::Twitter optarg;
        if ( TwitterFromPropertyBranch(
                response, &optarg, branch) )
        {
            response_data_ptr->twitter = std::move(optarg);
        }
    }
    catch(boost::property_tree::ptree_bad_path & err)
    {
        // Is optional
    }

    // create_content_struct_parse TSingle
    try {
        const boost::property_tree::wptree & branch =
            response->pt.get_child(L"response.user_info.gmail");

        ResponseData::Gmail optarg;
        if ( GmailFromPropertyBranch(
                response, &optarg, branch) )
        {
            response_data_ptr->gmail = std::move(optarg);
        }
    }
    catch(boost::property_tree::ptree_bad_path & err)
    {
        // Is optional
    }

    // Only on success, return parsed data structure with response
    response->response_data = std::move(response_data);

#   undef return_error
}

mf::http::SharedBuffer::Pointer Impl::GetPostData()
{
    std::map<std::string, std::string> parts;


    std::string post_data = MakePost(api_path + ".php", parts);
    AddDebugText(" POST data: " + post_data + "\n");
    return mf::http::SharedBuffer::Create(post_data);
}

// Request ---------------------------------------------------------------------

Request::Request() :
    impl_(new Impl())
{
}

void Request::SetCallback( CallbackType callback_function )
{
    impl_->SetCallback(callback_function);
}

void Request::HandleContent(
        const std::string & url,
        const mf::http::Headers & headers,
        const std::string & content
    )
{
    impl_->HandleContent(url, headers, content);
}

void Request::HandleError(
        const std::string & url,
        std::error_code ec,
        const std::string & error_string
    )
{
    impl_->HandleError(url, ec, error_string);
}

std::string Request::Url(const std::string & hostname) const
{
    return impl_->Url(hostname);
}

void Request::SetSessionToken(
        std::string session_token,
        std::string time,
        int secret_key
    )
{
    impl_->SetSessionToken(session_token, time, secret_key);
}

mf::http::SharedBuffer::Pointer Request::GetPostData()
{
    return impl_->GetPostData();
}

}  // namespace v1_3
}  // namespace get_info
}  // namespace user
}  // namespace api
}  // namespace mf
