/**
 * @file update.cpp
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
// #define OUTPUT_DEBUG
#include "v1_5.hpp"

#include <string>

#include "mediafire_sdk/api/error.hpp"
#include "mediafire_sdk/api/ptree_helpers.hpp"
#include "mediafire_sdk/utils/string.hpp"
#include "mediafire_sdk/api/session_token_api_base.hpp"

#include "boost/property_tree/json_parser.hpp"

namespace v1_5 = mf::api::file::update::v1_5;


namespace {
std::string AsString(const v1_5::Privacy & value)
{
    if (value == v1_5::Privacy::Public)
        return "public";
    if (value == v1_5::Privacy::Private)
        return "private";
    return mf::utils::to_string(static_cast<uint32_t>(value));
}
std::string AsString(const v1_5::Truncate & value)
{
    if (value == v1_5::Truncate::No)
        return "no";
    if (value == v1_5::Truncate::Yes)
        return "yes";
    return mf::utils::to_string(static_cast<uint32_t>(value));
}
}  // namespace

#include "mediafire_sdk/api/type_helpers.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
namespace update {
namespace v1_5 {

const std::string api_path("/api/1.5/file/update");

// Impl ------------------------------------------------------------------------

class Impl : public SessionTokenApiBase<Response>
{
public:


    boost::optional<std::string> quickkey_;
    boost::optional<std::string> filepath_;
    boost::optional<std::string> filename_;
    boost::optional<std::string> description_;
    boost::optional<Privacy> privacy_;
    boost::optional<Truncate> truncate_;
    boost::optional<boost::posix_time::ptime> mtime_;
    virtual void BuildUrl(
        std::string * path,
        std::map<std::string, std::string> * query_parts
    ) const override;

    virtual void ParseResponse( Response * response ) override;

    mf::http::SharedBuffer::Pointer GetPostData();

    mf::api::RequestMethod GetRequestMethod() const
    {
        return mf::api::RequestMethod::Post;
    }
};


void Impl::BuildUrl(
            std::string * path,
            std::map<std::string, std::string> * query_parts
    ) const
{
    *path = api_path + ".php";
}

void Impl::ParseResponse( Response * response )
{
    // This function uses return defines for readability and maintainability.
#   define return_error(error_type, error_message)                             \
    {                                                                          \
        SetError(response, error_type, error_message);                         \
        return;                                                                \
    }

    ResponseData response_data;

    // For uniformity for code generation with the other content parsers.
    ResponseData * response_data_ptr = &response_data;

    // create_content_parse_single optional no default
    {
        uint32_t optarg;
        if ( GetIfExists(
                response->pt,
                "response.new_device_revision",
                &optarg) )
        {
            response_data_ptr->new_device_revision = optarg;
        }
    }

    // Only on success, return parsed data structure with response
    response->response_data = std::move(response_data);

#   undef return_error
}

mf::http::SharedBuffer::Pointer Impl::GetPostData()
{
    std::map<std::string, std::string> parts;

    if (quickkey_)
        parts["quick_key"] = *quickkey_;
    if (filepath_)
        parts["file_path"] = *filepath_;
    if (filename_)
        parts["filename"] = *filename_;
    if (description_)
        parts["description"] = *description_;
    if (privacy_)
        parts["privacy"] = AsString(*privacy_);
    if (truncate_)
        parts["truncate"] = AsString(*truncate_);
    if (mtime_)
        parts["mtime"] = AsString(*mtime_);

    std::string post_data = MakePost(api_path + ".php", parts);
    AddDebugText(" POST data: " + post_data + "\n");
    return mf::http::SharedBuffer::Create(post_data);
}

// Request ---------------------------------------------------------------------

Request Request::FromQuickKey(
        std::string quickkey
    )
{
    Request request;
    request.impl_->quickkey_ = std::move(quickkey);
    return request;
}


Request Request::FromFilePath(
        std::string filepath
    )
{
    Request request;
    request.impl_->filepath_ = std::move(filepath);
    return request;
}


Request::Request() :
    impl_(new Impl())
{
}

void Request::SetCallback( CallbackType callback_function )
{
    impl_->SetCallback(callback_function);
}

void Request::HandleContent(
        const std::string & url,
        const mf::http::Headers & headers,
        const std::string & content
    )
{
    impl_->HandleContent(url, headers, content);
}

void Request::HandleError(
        const std::string & url,
        std::error_code ec,
        const std::string & error_string
    )
{
    impl_->HandleError(url, ec, error_string);
}

std::string Request::Url(const std::string & hostname) const
{
    return impl_->Url(hostname);
}

void Request::SetSessionToken(
        std::string session_token,
        std::string time,
        int secret_key
    )
{
    impl_->SetSessionToken(session_token, time, secret_key);
}

void Request::SetQuickkey(std::string quickkey)
{
    impl_->quickkey_ = quickkey;
}

void Request::SetFilepath(std::string filepath)
{
    impl_->filepath_ = filepath;
}

void Request::SetFilename(std::string filename)
{
    impl_->filename_ = filename;
}

void Request::SetDescription(std::string description)
{
    impl_->description_ = description;
}

void Request::SetPrivacy(Privacy privacy)
{
    impl_->privacy_ = privacy;
}

void Request::SetTruncate(Truncate truncate)
{
    impl_->truncate_ = truncate;
}

void Request::SetMtime(boost::posix_time::ptime mtime)
{
    impl_->mtime_ = mtime;
}

mf::http::SharedBuffer::Pointer Request::GetPostData()
{
    return impl_->GetPostData();
}

}  // namespace v1_5
}  // namespace update
}  // namespace file
}  // namespace api
}  // namespace mf
